default_platform(:ios)

platform :ios do

  before_all do
      
    setup_ci

    xcode_select("/Applications/Xcode_16.4.app")

  end

  desc "Submit a new Beta apk for testing"
  lane :beta do

    filename = "patricias.ipa"

    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_KEY_ID"],
      issuer_id: ENV["APPLE_KEY_ISSUER_ID"],
      key_filepath: "AuthKey.p8",
    )

    match(
      readonly: true,
      git_basic_authorization: Base64.strict_encode64(ENV["MATCH_GIT_TOKEN"]),
      api_key: api_key,
    )


    build_app(
      workspace: "patricias.xcworkspace",
      scheme: "patricias",
      clean: true,
      silent: true,
      output_directory: File.dirname(filename),
      output_name: File.basename(filename),
      export_method: "app-store",
      export_team_id: ENV["APPLE_TEAM_ID"],
      export_options: {
        provisioningProfiles: {
          "#{ENV["IOS_PACKAGE_NAME"]}" => "match AppStore #{ENV["IOS_PACKAGE_NAME"]}",
        },
      }
    )

    # upload_to_testflight(
    #   api_key: api_key,
    #   ipa: File.join(File.dirname(filename), File.basename(filename)),
    #   changelog: "Happy Testing !!!😄",
    #   groups: ENV["IOS_TEST_GROUPS"],
    #   distribute_external: true,
    #   beta_app_description: "mCommerce application",
    #   beta_app_feedback_email: "christian@djeukeu.com",
    #   beta_app_review_info: {
    #     contact_email: "christian@djeukeu.com",
    #     contact_first_name: "Christian",
    #     contact_last_name: "Djeukeu",
    #     contact_phone: "+4407474926221",
    #     notes: "Happy Testing !!!😄"
    #   },
    #   localized_app_info: {
    #     "default": {
    #       feedback_email: "christian@djeukeu.com",
    #       marketing_url: "https://patriciaskinscentsecrets.com",
    #       privacy_policy_url: "https://patriciaskinscentsecrets.com/privacy-policy/",
    #       description: "Default description",
    #     },
    #     "en-GB": {
    #       feedback_email: "christian@djeukeu.com",
    #       marketing_url: "https://patriciaskinscentsecrets.com",
    #       privacy_policy_url: "https://patriciaskinscentsecrets.com/privacy-policy/",
    #       description: "Default description",
    #     },
    #   }
    # )

  end
end
