name: Android Beta App Deployment
run-name: ${{ github.actor }} triggered the Android Beta Deployment

on:
  push:
    branches:
      - develop


env:
  APP_ENV: ${{ vars.APP_ENV }}

jobs:
  android:
    environment: 'STAGING'
    name: Build Android
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Version Code
        id: version_code
        run: |
          echo "::set-output name=number::$(git rev-list --count HEAD)"
      - uses: xt0rted/setup-dotnet@v1.0.0
      - name: Install Gitversion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.12.0'
      - name: Use Gitversion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          configFilePath: GitVersion.yml
          useConfigFile: true
      - name: Display GitVersion outputs
        run: |
          echo "version_code: ${{ steps.version_code.outputs.number }}"
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.commitsSinceVersionSource }}"
