name: Lint CI
run-name: ${{ github.actor }} triggered the lint CI

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  run-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 23.7.0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: lint
        run: |
          yarn 
          yarn lint
